/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_intel_csdk_wrapper_JNIMediator */
typedef enum
{
STC_ERROR_WIFI_NOT_AVAILABLE = -5,
STC_ERROR_BLUETOOTH_NOT_AVAILABLE,
STC_ERROR_INTERNET_NOT_AVAILABLE,
STC_ERROR_APPLICATION_ID,
STC_ERROR_CLIENT_ID,
STC_ERROR_CLIENT_SECRET,
STC_ERROR_ARGUMENT_ERROR,
STC_ERROR_INITIALIZE_FAIL,
STC_ERROR_DISCOVERU_FAIL,
}StcError;

#ifndef _Included_com_intel_csdk_wrapper_JNIMediator
#define _Included_com_intel_csdk_wrapper_JNIMediator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_intel_csdk_wrapper_JNIMediator
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeInit
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_intel_csdk_wrapper_JNIMediator
 * Method:    nativeIdentity
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeIdentity
  (JNIEnv *, jobject, jstring, jstring, jbyteArray,jint);

/*
 * Class:     com_intel_csdk_wrapper_JNIMediator
 * Method:    nativePeerInvitation
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativePeerInvitation
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_intel_csdk_wrapper_JNIMediator
 * Method:    nativeInviteStatus
 * Signature: (Ljava/util/UUID;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeInviteStatus
  (JNIEnv *, jobject, jstring, jlong, jboolean);

/*
 * Class:     com_intel_csdk_wrappjlonger_JNIMediator
 * Method:    nativeSendMsg
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeSendMsg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_intel_csdk_wrapper_JNIMediator
 * Method:    nativeDisconnectPeer
 * Signature: (Ljava/util/UUID;)J
 */
JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeDisconnectPeer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_intel_csdk_wrapper_JNIMediator
 * Method:    nativeDestroyConnection
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeDestroyConnection
  (JNIEnv *, jobject);

JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeRegisterDiscovery();

JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeRegisterCommunication();

JNIEXPORT jint JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeConnectNode
  (JNIEnv *, jobject, jstring, jboolean);

JNIEXPORT jint JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeDisconnectNode
  (JNIEnv *, jobject, jstring);

JNIEXPORT jlong JNICALL Java_com_intel_csdk_wrapper_JNIMediator_nativeQueryCloudStatus();

#ifdef __cplusplus
}
#endif
#endif
